# -*- coding: utf-8 -*-
"""Cópia de Calculadora

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/130MCXQbB4iwnXVVi39xe_aRl5mjKYMY-

# **Calculadora**
"""

num1 = int(input('Digite o primeiro número '))
operacao = input('escolha qual operação deseja fazer ')
num2 = int(input('Digite o segundo número '))

if operacao == "+":
   resultado = (num1 + num2)
   print("O resultado é:", resultado)
elif operacao == "-":
  resultado = (num1 - num2)
  print("O resultado é:", resultado)
elif operacao == "*":
  resultado = (num1 * num2)
  print("O resultado é:", resultado)
elif operacao == "/":
  resultado = (num1 / num2)
  print("O resultado é:", resultado)
else:
  print("Operação inválida!")