# -*- coding: utf-8 -*-
Calculadora

Automatically generated by Colab.


# **Calculadora**
"""

num1 = int(input('Digite o primeiro número '))
operacao = input('escolha qual operação deseja fazer ')
num2 = int(input('Digite o segundo número '))

if operacao == "+":
   resultado = (num1 + num2)
   print("O resultado é:", resultado)
elif operacao == "-":
  resultado = (num1 - num2)
  print("O resultado é:", resultado)
elif operacao == "*":
  resultado = (num1 * num2)
  print("O resultado é:", resultado)
elif operacao == "/":
  resultado = (num1 / num2)
  print("O resultado é:", resultado)
else:
  print("Operação inválida!")
